### ISSUE TITLE
Subscribing to the feed throws exception and doesn't show a message

### ISSUE THREAD

**Issue by salihgueler** [GetStream/stream-feed-flutter#89]
**Describe the bug**
When the user subscribes to the feed, if there is a new event, it throws an error. 
`Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String?' in type cast`

**What version of Flutter do you use?**
Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale en-TR)

**What package are you using? What version?**
  stream_feed: ^0.2.1

**What platform is it about?**
Only tested on
- [x] MacOS

**a copy of `flutter doctor --verbose`**
```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale en-TR)
    • Flutter version 2.2.1 at /Users/salih/Desktop/flutter
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/salih/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 15.0.1+9-18)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Users/salih/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7717.56.2111.7361063/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Users/salih/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.77
```

**To Reproduce**
1. Run the following code
```
 final _streamFeedClient = StreamFeedClient.connect(
   <api-key>
    token: token,
    appId: <appId>,
  );
  final feed = _streamFeedClient.notificationFeed('user', userId);
  final activity = Activity(
    actor: createUserReference(userId),
    verb: 'created',
    object: 'created',
    time: DateTime.now(),
    extraData: {
      "createdTask": task.toJson(),
    },
  );
  feed.addActivity(activity);
  feed.subscribe((message) {
    print('message in a bottle $message');
  });
```
2. Add a new activity to the feed.
3. 
**Expected behavior**
It should print "message in a bottle" with a message variable.

**Logs **
```
flutter: *** Request ***
flutter: uri: https://api.stream-io-api.com/api/v1.0/feed/task/32db0f46-3593-4e14-aa57-f05af4887260/?api_key=yn6bquc5zs6m&location=unspecified
flutter: method: POST
flutter: responseType: ResponseType.json
flutter: followRedirects: true
flutter: connectTimeout: 10000
flutter: sendTimeout: 0
flutter: receiveTimeout: 10000
flutter: receiveDataWhenStatusError: true
flutter: extra: {}
flutter: headers:
flutter:  stream-auth-type: jwt
flutter:  x-stream-client: stream-feed-dart-client-macos-0.2.1
flutter:  Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjMyNzE0NTMsImlhdCI6MTYyMzI3MDI1MywidXNlcl9pZCI6IjMyZGIwZjQ2LTM1OTMtNGUxNC1hYTU3LWYwNWFmNDg4NzI2MCJ9.UNxSVBQLpFLiGqFz8rUePQJdsvKmtt8ipe-9Kt2jsTc
flutter:  content-type: application/json; charset=utf-8
flutter: data:
flutter: Activity(SU:32db0f46-3593-4e14-aa57-f05af4887260, task_situation_updated to true, updated, null, null, null, null, 2021-06-09 23:24:18.238189, null, null, null, null, {createdTask: {"id": "32db0f46-3593-4e14-aa57-f05af4887260", "title": "KeyPack", "isFinished": true}})
flutter: 
flutter: *** Response ***
flutter: uri: https://api.stream-io-api.com/api/v1.0/feed/task/32db0f46-3593-4e14-aa57-f05af4887260/?api_key=yn6bquc5zs6m&location=unspecified
flutter: statusCode: 201
flutter: headers:
flutter:  connection: keep-alive
flutter:  cache-control: no-cache
flutter:  date: Wed, 09 Jun 2021 20:24:19 GMT
flutter:  access-control-allow-origin: *
flutter:  x-ratelimit-limit: 1000
flutter:  x-ratelimit-reset: 1623270300
flutter:  x-ratelimit-remaining: 998
flutter:  content-type: application/json;charset=utf-8
flutter:  access-control-max-age: 86400
flutter:  server: nginx
flutter:  access-control-allow-headers: x-requested-with, content-type, accept, origin, authorization, x-csrftoken, x-stream-client, stream-auth-type
flutter:  access-control-allow-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
flutter:  content-length: 366
flutter: Response Text:
flutter: {"actor":"SU:32db0f46-3593-4e14-aa57-f05af4887260","createdTask":"{\"id\": \"32db0f46-3593-4e14-aa57-f05af4887260\", \"title\": \"KeyPack\", \"isFinished\": true}","duration":"6.90ms","foreign_id":"","id":"cff95542-c979-11eb-8080-80005abdd229","object":"task_situation_updated to true","origin":null,"target":"","time":"2021-06-09T23:24:18.238189","verb":"updated"}
flutter: 
flutter: (2021-06-09 23:24:18.877664) ℹ️ 🕒 received message : {data: {deleted: [], deleted_foreign_ids: [], feed: task:32db0f46-3593-4e14-aa57-f05af4887260, new: [{actor: {error: ReferenceNotFound, id: 32db0f46-3593-4e14-aa57-f05af4887260, reference: SU:32db0f46-3593-4e14-aa57-f05af4887260, reference_type: user}, createdTask: {"id": "32db0f46-3593-4e14-aa57-f05af4887260", "title": "KeyPack", "isFinished": true}, foreign_id: , group: updated_2021-06-09, id: cff95542-c979-11eb-8080-80005abdd229, object: task_situation_updated to true, origin: null, target: , time: 2021-06-09T23:24:18.238189, verb: updated}]}, channel: /site-1128601-feed-task32db0f46-3593-4e14-aa57-f05af4887260, successful: false}
flutter: (2021-06-09 23:24:18.877872) ℹ️ 🕒 Client 1-4add16cf-2e01-4a95-b84e-2782369ab005 calling listeners for /site-1128601-feed-task32db0f46-3593-4e14-aa57-f05af4887260 with {deleted: [], deleted_foreign_ids: [], feed: task:32db0f46-3593-4e14-aa57-f05af4887260, new: [{actor: {error: ReferenceNotFound, id: 32db0f46-3593-4e14-aa57-f05af4887260, reference: SU:32db0f46-3593-4e14-aa57-f05af4887260, reference_type: user}, createdTask: {"id": "32db0f46-3593-4e14-aa57-f05af4887260", "title": "KeyPack", "isFinished": true}, foreign_id: , group: updated_2021-06-09, id: cff95542-c979-11eb-8080-80005abdd229, object: task_situation_updated to true, origin: null, target: , time: 2021-06-09T23:24:18.238189, verb: updated}]}
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String?' in type cast
#0      _$ActivityFromJson (package:stream_feed/src/core/models/activity.g.dart:11:26)
#1      new Activity.fromJson (package:stream_feed/src/core/models/activity.dart:33:7)
#2      _$RealtimeMessageFromJson.<anonymous closure> (package:stream_feed/src/core/models/realtime_message.g.dart:17:30)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#7      new List.of (dart:core-patch/array_patch.dart:50:28)
#8      ListIterable.toList (dart:_internal/iterable.dart:212:44)
#9      _$RealtimeMessageFromJson (package:stream_feed/src/core/models/realtime_message.g.dart:20:10)
#10     new RealtimeMessage.fromJson (package:stream_feed/src/core/models/realtime_message.dart:26:7)
#11     Feed.subscribe.<anonymous closure> (package:stream_feed/src/client/feed.dart:76:47)
#12     Subscription.call (package:faye_dart/src/subscription.dart:21:16)
#13     EventEmitter.emit (package:faye_dart/src/event_emitter.dart:59:23)
#14     Channel.trigger (package:faye_dart/src/channel.dart:26:50)
#15     ChannelMapX.distributeMessage (package:faye_dart/src/channel.dart:103:22)
#16     FayeClient._deliverMessage (package:faye_dart/src/client.dart:430:15)
#17     FayeClient._receiveMessage.<anonymous closure> (package:faye_dart/src/client.dart:409:7)
#18     Extensible.pipeThroughExtensions.pipe (package:faye_dart/src/extensible.dart:29:46)
#19     Extensible.pipeThroughExtensions.pipe (package:faye_dart/src/extensible.dart:32:34)
#20     Extensible.pipeThroughExtensions (package:faye_dart/src/extensible.dart:37:9)
#21     FayeClient._receiveMessage (package:faye_dart/src/client.dart:406:5)
#22     FayeClient._onDataReceived (package:faye_dart/src/client.dart:169:7)
#23     _rootRunUnary (dart:async/zone.dart:1362:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#28     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#29     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:256:10)
#30     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#31     _rootRunUnary (dart:async/zone.dart:1362:47)
#32     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#37     _StreamController._add (dart:async/stream_controller.dart:607:7)
#38     _rootRunUnary (dart:async/zone.dart:1362:47)
#39     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#44     _StreamController._add (dart:async/stream_controller.dart:607:7)
#45     _StreamController.add (dart:async/stream_controller.dart:554:5)
#46     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#47     _rootRunUnary (dart:async/zone.dart:1362:47)
#48     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#52     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#53     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#54     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#55     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#56     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#57     _rootRunUnary (dart:async/zone.dart:1362:47)
#58     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#62     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#63     _StreamController._add (dart:async/stream_controller.dart:607:7)
#64     _StreamController.add (dart:async/stream_controller.dart:554:5)
#65     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#66     _rootRunUnary (dart:async/zone.dart:1362:47)
#67     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#68     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#69     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#70     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#71     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#72     _StreamController._add (dart:async/stream_controller.dart:607:7)
#73     _StreamController.add (dart:async/stream_controller.dart:554:5)
#74     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
#75     _rootRun (dart:async/zone.dart:1346:47)
#76     _CustomZone.run (dart:async/zone.dart:1258:19)
#77     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#78     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#79     _rootRun (dart:async/zone.dart:1354:13)
#80     _CustomZone.run (dart:async/zone.dart:1258:19)
#81     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
#82     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#83     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#84     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#85     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Instance of 'Error'
#0      EventEmitter.emit (package:faye_dart/src/event_emitter.dart:75:19)
#1      Channel.trigger (package:faye_dart/src/channel.dart:26:50)
#2      ChannelMapX.distributeMessage (package:faye_dart/src/channel.dart:103:22)
#3      FayeClient._deliverMessage (package:faye_dart/src/client.dart:430:15)
#4      FayeClient._receiveMessage.<anonymous closure> (package:faye_dart/src/client.dart:409:7)
#5      Extensible.pipeThroughExtensions.pipe (package:faye_dart/src/extensible.dart:29:46)
#6      Extensible.pipeThroughExtensions.pipe (package:faye_dart/src/extensible.dart:32:34)
#7      Extensible.pipeThroughExtensions (package:faye_dart/src/extensible.dart:37:9)
#8      FayeClient._receiveMessage (package:faye_dart/src/client.dart:406:5)
#9      FayeClient._onDataReceived (package:faye_dart/src/client.dart:169:7)
#10     _rootRunUnary (dart:async/zone.dart:1362:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#16     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:256:10)
#17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#18     _rootRunUnary (dart:async/zone.dart:1362:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#24     _StreamController._add (dart:async/stream_controller.dart:607:7)
#25     _rootRunUnary (dart:async/zone.dart:1362:47)
#26     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#31     _StreamController._add (dart:async/stream_controller.dart:607:7)
#32     _StreamController.add (dart:async/stream_controller.dart:554:5)
#33     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#34     _rootRunUnary (dart:async/zone.dart:1362:47)
#35     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#41     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#42     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#44     _rootRunUnary (dart:async/zone.dart:1362:47)
#45     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#50     _StreamController._add (dart:async/stream_controller.dart:607:7)
#51     _StreamController.add (dart:async/stream_controller.dart:554:5)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#53     _rootRunUnary (dart:async/zone.dart:1362:47)
#54     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#58     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#59     _StreamController._add (dart:async/stream_controller.dart:607:7)
#60     _StreamController.add (dart:async/stream_controller.dart:554:5)
#61     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
#62     _rootRun (dart:async/zone.dart:1346:47)
#63     _CustomZone.run (dart:async/zone.dart:1258:19)
#64     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#65     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#66     _rootRun (dart:async/zone.dart:1354:13)
#67     _CustomZone.run (dart:async/zone.dart:1258:19)
#68     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
#69     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#70     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#71     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```
**Additional context**

**Comment by xsahil03x** [comment]
Hey @salihgueler, thanks for reporting. It's a known bug that our team have to discuss upon. I'll let you know tomorrow once we come to a conclusion.

**Comment by sachaarbonel** [comment]
Hey @salihgueler, thanks for the feedback. As Sahil said we had to discuss this and we have a fix ready in this PR #90. 
Would you mind try it and let us know if it worked for you?
```yaml
dependencies:   
  stream_feed:
     git:
       url: https://github.com/GetStream/stream-feed-flutter.git
       ref: fix-issue-89
       path: ./packages/stream_feed
```

**Comment by salihgueler** [comment]
HI @sachaarbonel, it seems to be working now :)

**Comment by rlee1990** [comment]
@sachaarbonel I am using the version you posted but I still cannot get enriched activities no errors it just does not have an option for them.

**Comment by sachaarbonel** [comment]
The API for EnrichedActivity still needs some work but basically, to extract an object this is how it's done for now: 
```dart
(EnrichableField.serialize(activity.object)
            as Map<String, Object?>)["comment"] as String)
```

**Comment by rlee1990** [comment]
Thank you @sachaarbonel

**Comment by rlee1990** [comment]
@sachaarbonel Im not sure I get you but for the subscription api it only returns activities and not enriched activities. The message you posted not sure how that will allow me to use that in this way.

**Comment by xsahil03x** [comment]
Hey @rlee1990 , the subscription activity type depends on the type of activity you are adding in feed. So if you add an activity with enriched fields you will get the same in subscription callback.

**Comment by rlee1990** [comment]
@xsahil03x thats not the case as one the RealtimeMessage.newActivities is a list of type Activity and not a type of EnrichedActivity so I am just trying to find out if its possible to also add EnrichedActivity as a type for that or will I need to completely change up my code and just get activities back and then make a call to get the enriched data later (which would be a lot more network calls).

**Comment by xsahil03x** [comment]
Also, do note that new activities coming from subscription will only contain enrichment for these fields:

1. Activity `SA`
2. Reaction `SR`
3. Object `SO`
4. User `SU`

the only thing you don’t get is the enriched reactions like own_reaction or latest_reactions

**Comment by xsahil03x** [comment]
Hey @rlee1990, can you open a separate one for your issue?
